### ISSUE TITLE
Phenothiazine

### ISSUE THREAD

**Issue by drc007** [OpenSourceMycetoma/Series-3-Phenothiazines#1]
There are many phenothiazines available from commercial vendors, should be possible to scope out SAR without needing to make any compounds.

**Comment by MFernflower** [comment]
If you were to compile a list of commercially available phenothiazines and there prices I would be eternally gratefull!! @drc007

**Comment by drc007** [comment]
Go to [emolecules](https://www.emolecules.com) and paste this SMILES string into the search box at the top right hand corner 

N1c2ccccc2Sc2ccccc12

You should get a list of around 400 molecules together with vendors. I suspect you won't get prices until you show evidence that you are a customer ;-)

**Comment by MFernflower** [comment]
Indeed the N-alkyl phenothiazines are quite well represented!

**Comment by MFernflower** [comment]
@drc007 see issue #2 as I have found a supplier who has a good amount of molecules of interest in stock - closing this for now

**Comment by drc007** [comment]
Chlorpromazine was the precursor to the tricyclic group of drugs including imipramine 
![imipramine svg](https://user-images.githubusercontent.com/7080516/48721307-897fed00-ec19-11e8-8e7c-78f389e1766b.png)

**Comment by MFernflower** [comment]
Duly noted!

**Comment by mattodd** [comment]
When closing issues, always consider whether the act of closing will orphan the discussion. In this case not, because you've installed the forward link to Issue number 2. But it might be an idea to start the wiki page up for this series and capture this discussion (plus any follow-ons) in a section on the wiki around commercial sourcing of compounds, perhaps in a general wiki section on how to source compounds?
