### ISSUE TITLE
Patents

### ISSUE THREAD

**Issue by drc007** [OpenSourceMycetoma/Series-3-Phenothiazines#4]
In the readme it is stated there are no patents, I suspect there are hundreds of patents covering these type of tricyclics.

**Comment by MFernflower** [comment]
Since I really do not know much at all about US drug laws (I come from the chemistry side of things as you may know) I presumed that since it seems that every tom dick and harry has there own generic formulations of CPZ and imipramine (at least in the US) alongside the age of the drugs that there would be no IP affecting us should our S3 drugs ever miraculously come to market @drc007

**Comment by drc007** [comment]
Not the same as no patents though. Whilst the original patents may have expired, you may well find there are filings on related compounds, combinations or formulations that are still in place. I never presume anything when it comes to IP.

**Comment by MFernflower** [comment]
You are wise to assume nothing is logical in IP - I will remove that note from the readme - Just as a look ahead do we have partners who can offer legal advice on both the S1 and S3 projects? @drc007 @mattodd As fenarimol is a known big box agricultural chemical

**Comment by mattodd** [comment]
We do not, but there are major resources in DNDi @bendndi that could be drawn upon were there significant worries in this regard, e.g. over unintentional infringement. For other projects e.g. in OSM we are fairly sure we're in a patent-free zone. For new series in mycetoma my default assumption is that we would be highly unlikely to infringe anything since we are pursuing a specific application (mycetoma) for which there are unlikely to be patents. However, what if we examine structures that are of interest for broader antifungal projects for which there are active patents, and we stumble upon those structures?

**Comment by bendndi** [comment]
I would not worry about patent issues. Concentrate on getting the science right, worry about IP later. There are always solution to IP issues.
As an aside, anything which sat within the known "tricyclic" space could not be repurposed for mycetoma because of the brain penetration issue - repurposing CNS actives in a non CNS indication (at least in infectious disease) would be a no go.

**Comment by MFernflower** [comment]
@bendndi Even if the novel compound crosses the BBB but has no effect on neural receptors?

**Comment by bendndi** [comment]
@mfernflower I’m talking about compounds with known CNS activity, but generally even if there is no obvious sign from in vitro receptogram, it’s a bad idea (if not a killer) to have brain exposure in a compound with no need for CNS penetration. Too risky, and brain biochemistry is too capricious to risk messing with it for no reason.

**Comment by MFernflower** [comment]
Well at this point we have not progressed into custom compound synthesis but I feel there are ways to mitigate CNS infiltration when we get there

Our current line of work is simply testing if known antifungal tricyclic neurological drugs show any effect on Madurella

**Comment by MFernflower** [comment]
@bendndi I also wonder if series 1 compounds would cross BBB as they are
quite planar and oily - perhaps CNS avoidance is the central rule of
mycetoma drug development @mattodd 

Using some online tools it appears it is likely that the S1 compounds are likely to enter brain tissue
